---
- hosts: all
  become: yes
  tasks:
    - name: Update all packages
      apt:
        state: latest
        force_apt_get: yes
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
    
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Execute shell script on ec2 machine(s)
      shell:
        cmd: |
          echo '<!doctype html>
             <html lang="en"><h1>Home page!</h1></br>
             <h3>(Instance A)</h3>
             </html>' | sudo tee /var/www/html/index.html
      register: result
    - name: Show result
      debug:
        msg: "{{ result.stdout }}"